In [6]:
!pip install tqdm

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable


In [5]:
import rospy
from sensor_msgs.msg import Imu
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm


CatBot Lab Context: This notebook supports the CatBot course and focuses on Measure IMU sensor.

# Measure IMU sensor

rosrun rosserial_python serial_node.py /dev/ttyACM0

In [37]:



max_samples = 1000

rospy.init_node('imuData_analysis', anonymous=True)
lin_acc  = np.zeros([3, max_samples])
ang_vel  = np.zeros([3, max_samples])
quat_rot = np.zeros([4, max_samples])

for i in tqdm(range(max_samples)):
    
    msg = rospy.wait_for_message('/catbot/imu_data', Imu, 10)
    
    quat_rot[0,i] = msg.orientation.x
    quat_rot[1,i] = msg.orientation.y
    quat_rot[2,i] = msg.orientation.z
    quat_rot[3,i] = msg.orientation.w
    
    ang_vel[0,i] = msg.angular_velocity.x
    ang_vel[1,i] = msg.angular_velocity.y
    ang_vel[2,i] = msg.angular_velocity.z
    
    lin_acc[0,i] = msg.linear_acceleration.x
    lin_acc[1,i] = msg.linear_acceleration.y
    lin_acc[2,i] = msg.linear_acceleration.z



100%|██████████| 1000/1000 [00:46<00:00, 21.63it/s]


In [38]:
np.savetxt('data/imu_data_orientation.txt',         quat_rot)
np.savetxt('data/imu_data_angular_velocity.txt',    ang_vel)
np.savetxt('data/imu_data_linear_acceleration.txt', lin_acc)

In [39]:
quat_rot = np.loadtxt('data/imu_data_orientation.txt')
ang_vel  = np.loadtxt('data/imu_data_angular_velocity.txt')
lin_acc  = np.loadtxt('data/imu_data_linear_acceleration.txt')

In [43]:
quat_cov_matrix = np.cov(quat_rot)
print(quat_cov_matrix)

[[ 7.94243045e-07 -1.62756330e-08  2.28548325e-06 -1.54167435e-06]
 [-1.62756330e-08  6.05533073e-10 -4.47155805e-08  2.93039613e-08]
 [ 2.28548325e-06 -4.47155805e-08  6.68405412e-06 -4.50345262e-06]
 [-1.54167435e-06  2.93039613e-08 -4.50345262e-06  3.06000968e-06]]


# Linear acceleration covariance matrix

In [45]:
lin_acc_matrix = np.cov(lin_acc)
print(lin_acc_matrix)
np.savetxt('data/lin_acc_cov.txt', lin_acc_matrix)

[[ 0.0037571  -0.00159618  0.00247253]
 [-0.00159618  0.00242264 -0.00061926]
 [ 0.00247253 -0.00061926  0.03383873]]


In [4]:
import rospy
from sensor_msgs.msg import Imu
import numpy as np

msg = rospy.wait_for_message('/catbot/imu_data', Imu, timeout=1)


ROSException: timeout exceeded while waiting for message on topic /catbot/imu_data